PARSER_SRCDIR=codec/parser
PARSER_CPP_SRCS=\
	$(PARSER_SRCDIR)/src/h264parser.cpp

PARSER_OBJS += $(PARSER_CPP_SRCS:.cpp=.$(OBJ))
OBJS += $(PARSER_OBJS)

$(PARSER_SRCDIR)/%.$(OBJ): $(PARSER_SRCDIR)/%.cpp
	$(QUIET_CXX)$(CXX) $(CFLAGS) $(CXXFLAGS) $(INCLUDES) $(PARSER_CFLAGS) $(PARSER_INCLUDES) -c $(CXX_O) $<

ifeq (linux,$(OS))
$(LIBPREFIX)parser.$(LIBSUFFIX): $(PARSER_OBJS)
	$(QUIET)rm -f $@
	$(QUIET_AR)$(AR) $(AR_OPTS) $+

libraries: $(LIBPREFIX)parser.$(LIBSUFFIX)
LIBRARIES += $(LIBPREFIX)parser.$(LIBSUFFIX)
else
$(LIBPREFIX)parser.$(SHAREDLIBSUFFIX): $(PARSER_OBJS)
	$(QUIET_CXX)$(CXX) $(SHARED) $(CXX_LINK_O) $+ $(PARSER_LDFLAGS) $(LDFLAGS)

libraries: $(LIBPREFIX)parser.$(SHAREDLIBSUFFIX)
LIBRARIES += $(LIBPREFIX)parser.$(SHAREDLIBSUFFIX)
endif
